name: speednet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Deep Learning
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8

  # Computer Vision
  - opencv>=4.7.0
  - pillow>=9.0.0

  # Scientific Computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0

  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0

  # Jupyter (for development)
  - jupyter
  - jupyterlab
  - notebook

  # Utilities
  - tqdm>=4.62.0
  - click>=8.0.0
  - pathlib2
  - pyyaml>=6.0

  # Development tools
  - black
  - flake8
  - pytest

  # Pip dependencies
  - pip
  - pip:
    - ultralytics>=8.0.0
    - supervision>=0.16.0
    - roboflow
    - wandb
    - tensorboard
    - albumentations>=1.3.0
    - imgaug>=0.4.0
    - python-dotenv
    - rich
    - typer
    - fastapi
    - uvicorn
    - streamlit